// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304140850_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weathers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Mild",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Mild",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Warm",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Cool",
                            TemperatureC = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
